---
.travis.yml:
  docker_sets: 
  - set: docker/ubuntu-16.04
  - set: docker/ubuntu-14.04
  - set: docker/centos-7
  user: icann
  secure: "Npq3PSYJvAGcZeF8XYK8r1mQqJSF5HVNd2S/dqfomlGpDQSLNFEEbyWccaRTzRAvDWtbGk22QuN/MiWlpFIdXDAVc64szn7v1UeTwlQVRBfzp5QJhPbUKdQxf6Jqx4P3pqZ6FfZZDfKLVQmXQDGE+bn5cPZXkQr3RcyHzkAVWopYUdvPmbytyRnaiwVq3E3t5yVxA2GGsVPL7z3ZHLsF3S0b7BHyCwTir6lJiBNSb+WEEC1GXHpHr54gAY8D18o+Bvwq9E8ODEgNbYf42HEqpPU2sAd5vJ7A0vMTRLaIiGm2nAy8Zibtxk8AiR/kEPpSSKrp+LZl4ySsfJ4tH+aTkFaZVrxlYNfYBJ4jLhnoFo82gg8V3k2u+zlKqhvPFxPBcgADSq9gOEksu2+WoDx33hi4usZp5DUED9CDXGLovT/7E41z22CIpt6iRb0ppOTsM2YZcf5/NWmxsnMZg5XT3gO2iE4itL7DphQjmwnG12lwKfXn0SmALSNr3narszWewO3/4WO9CfHWvcGO2y5kptR7x5tudvygWBHjmmuc3AaBD1OktqkU/wCMiMrbCivsWjorYmx6jlgG/4fJIq0MXvUWDuYm+UO2r4VbZy69avFQ4AV8pHOb8vJ4rueeUfeZKyND/YiRfyWeyL0gM4tjrRhROsn8h4YA0PMC/2fAz+U="

